### ISSUE TITLE
Release of 0.4.2

### ISSUE THREAD

**Issue by NobodysNightmare** [wakoopa/activegraphql#11]
Hey there,

3 months ago you merged a pull request of me and immediately bumped the version of the gem to 0.4.2.

Today I just realized, that this version is not yet published on rubygems.org, 0.4.1 being the latest available.
Do you have any plans on releasing 0.4.2 there?

I would love to be able to get back to the official gem instead of our own fork.

Best regards
Jan

**Comment by menno** [comment]
Thanks for the reminder. I've pushed 0.4.2: https://rubygems.org/gems/activegraphql/versions/0.4.2

Cheers!
